### PR TITLE
Phase out 06

### PR DESCRIPTION
**Pull request by lrsantos11**
Makes HSL compatible with Julia v1.0. Built and tested on Julia v1.0.2

### CODE REVIEW

**Comment by lrsantos11** [comment]
Travis is failing on macOS with command 
```bash
julia --check-bounds=yes -e 'using Pkg; Pkg.add("BinDeps"); Pkg.add("Compat"); Pkg.build("BinDeps"); using BinDeps; BinDeps.debug("HSL")'
```
cuz' package `BinDeps` is not working correctly yet on Julia 1.0. Should we remove this line from travis directives?

**Comment by dpo** [comment]
Thank you, but what's the difference with #18, and why do we still need Compat?

**Comment by lrsantos11** [comment]
Man. Sorry for that. I reallly wanted to PR to #18. I'm a kind o newbie trying to learn GitHub magic. Can we manage to work. The difference is manly on the tests. And no, we don need Compat? Shame on me.

**Comment by dpo** [comment]
No shame at all!!! I'm having trouble with the TravisCI tests in #18. If we could resolve that, then you could PR the remaining diffs?!

**Comment by lrsantos11** [comment]
I cannot contribute to #18  probably because of permission issues. Could you arrange that or is better just for me to comment?

**Comment by dpo** [comment]
I'm not really seeing anything new compared to #18. Did I miss something? If not, let's close this and comment on #18.

**Comment by lrsantos11** [comment]
Ok. I'll close. However I still cannot make contributions to #18.

**Pull request closed without merging**
