### PR TITLE
Update available_hsl_algorithms

### PR DESCRIPTION
**Pull request by amontoison**
https://github.com/JuliaSmoothOptimizers/HSL.jl/actions/runs/3214926997/jobs/5255662792#step:6:88

### CODE REVIEW

**Comment by amontoison** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
Here, the JSOBot tests passed but for some reason, no comment was posted here.

@MonssafToukal Any ideas?

**Comment by amontoison** [comment]
Sometimes the comment is not posted because we call `@JSOBot runtests` just after the PR is opened (less than 1 minutes).

**Comment by amontoison** [comment]
@JSOBot runtests

**Review by dpo — APPROVED** [review]

**Pull request merged**
