### PR TITLE
allow compiler flags to be part of HSL_FC

### PR DESCRIPTION
**Pull request by dpo**
this is useful on Apple Silicon when compiling for x86_64,
among others, where HSL_FC = "gfortran -arch x86_64".

### CODE REVIEW

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
This PR includes CI on Apple Silicon running Julia and gcc/gfortran in x86_64 compatible mode via Rosetta. The build occurs with `HSL_FC="gfortran-7 -arch x86_64"`, which illustrates that flags can now be passed to the Fortran compiler.

**Comment by amontoison** [comment]
I suggest to add a variable `FFLAGS` by default.
```
FFLAGS = Sys.isapple() && Sys.ARCH === :aarch64 ? "-arch x86_64" : ""

**Comment by dpo** [comment]
I find that too restrictive. A different compiler on a different platform will have different flags. Also I'd like to avoid a proliferation of environment variables.

**Review by amontoison — APPROVED** [review]

**Comment by dpo** [comment]
If we do that, we'll also need `CFLAGS` and `LDFLAGS`. I see the point and I agree it's more general, but I suggest we add that feature when we need it.

**Comment by amontoison** [comment]
> I find that too restrictive. A different compiler on a different platform will have different flags. Also I'd like to avoid a proliferation of environment variables.

In that case, let the user changes `HSL_FC`.

**Comment by dpo** [comment]
> In that case, let the user changes HSL_FC when it's needed.

Yes, that's what this PR does.

**Pull request merged**
