### PR TITLE
makes HSL compatible with Julia v1.0

### PR DESCRIPTION
**Pull request by lrsantos11**
I made the changes so `Pkg.test("HSL")` passes on Julia v1.0.2

### CODE REVIEW

**Comment by dpo** [comment]
Thank you. What are the differences with #18?

**Comment by lrsantos11** [comment]
Good question. I don't know. I didn't notice that you were porting to. Please don't Merge. I'm trying to make it work on julia 0.6. 
We can compare between those PRs. 
You are phasing out Julia 0.6. I was trying to make compatible with both 0.6 and 1.0. 
@dpo  Do you think it is better to remove compatibility with Julia 0.6? If so, the work is much easier.

**Comment by lrsantos11** [comment]
Ok. I'll merge mine with phase-out branch.

**Comment by lrsantos11** [comment]
Ok. I'll try to merge my changes into #18.

**Comment by dpo** [comment]
I also created the [`ma57-phase-out-06` branch](https://github.com/JuliaSmoothOptimizers/HSL.jl/tree/ma57-phase-out-06) but haven't opened a pull request yet.

**Pull request closed without merging**
