### PR TITLE
[KB07] Add a Julia interface

### PR DESCRIPTION
**Pull request by amontoison**
Illustrate the goal of #129

### CODE REVIEW

**Comment by dpo** [comment]
I think we have to remove random tests.

**Comment by amontoison** [comment]
> I think we have to remove random tests.

We could fix the random seed as a temporary fix.

**Comment by amontoison** [comment]
`KB07` is not the most the relevant `HSL` package but I just wanted to test the modifications of #129

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
hmm we don't see the kb07 tests on linux

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
@MonssafToukal the bot isn't giving feedback. Any ideas?

**Comment by MonssafToukal** [comment]
> @MonssafToukal the bot isn't giving feedback. Any ideas?

So it seems the issue is because I made a mistake in the jenkinsfile. It's not Jenkins's fault unfortunately for me...

**Comment by dpo** [comment]
Fixable in finite time?

**Comment by dpo** [comment]
@amontoison Could you please rebase this branch?

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
