### PR TITLE
Updates to MA57 according to master

### PR DESCRIPTION
**Pull request by abelsiqueira**
This branch was built during my stay, and should be the rebased and updated `ma57` branch.

So, actually, what I'm proposing is to reset the `ma57` branch and use the new commits.

Alternatively, I can PR against `master` and we can start having `ma57` on master.

### CODE REVIEW

**Comment by dpo** [comment]
Is it possible to apply your changes to the `ma57-phase-out-06` branch? Then we could rebase `ma57` against that, and finally merge with `master`.

**Comment by abelsiqueira** [comment]
Correction: this seems to be a rebase of the `ma57-phase-out-06` branch, though some confusion ensues:
- The branches `jso/ma57` and `abel/ma57` both start with *"initial support for hsl_ma57"* (though they're different, see below);
- All commits from `jso/ma57` are included in `abel/ma57`;
- The commit *"MA57: phase out julia 0.6"* from `jso/ma57-phase-out-06` is included in `abel/ma57`;
- The next commit, *"Avoid building BLAS and metis ..."* is already on `master`;

In this branch I essentially rebased against the `BinaryProvider` master changes, and I made the change to `BinaryProvider` during rebasing.
In other words, in the `jso/ma57` branch, MA57 is added and built with `BinDeps`, and here I changed that first commit so that MA57 is added and built with `BinaryProvider` from the start.

- [First commit in `ma57` branch](https://github.com/JuliaSmoothOptimizers/HSL.jl/commit/048dc8d8c45b1a17cf96c6003418cc67948008e1)
- [First commit in `abel/ma57` branch](https://github.com/abelsiqueira/HSL.jl/commit/53ebdc476bbacb286b7c3e79c67a9c692f948c42)

This changes the history of the branch, but since the first commit on the branch is already breaking, I think that's the best alternative. Otherwise, we rebase without fixing MA57 during rebasing, and make a new commit just for these fixes.

**Comment by dpo** [comment]
This is extremely confusing and I don't even understand the order of the commits. I think we should start fresh from the `ma57` branch. Let's rebase it against `master`, and cherry-pick your commits.

**Comment by abelsiqueira** [comment]
Do you mean rebase, but don't fix BinDeps nor Julia update, and after make commits fixing them?

**Pull request closed without merging**
