### PR TITLE
Update CI_M1.yml

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
So this is where I'm a little confused because Julia 1.6 and 1.7 are based on libgfortran4, whereas Julia ≥ 1.8 is on libgfortran5. And I use gcc/gfortran-7 in all cases, which are based on libgfortran4.

**Comment by amontoison** [comment]
Even if Julia is compiled with `libgfortran5` the artifacts seem to detect the libgfortran available with your gcc/gfortran.

On my computer with gcc 11.2, `libopenblas.so` points to two `libgfortran` with Julia ≥ 1.8.
```
-> Julia 1.8
shell> ldd "/home/alexis/.julia/artifacts/7fca6a59f5903d74ab82fd8c36b7656125da4318/lib/libopenblas.so"
	linux-vdso.so.1 (0x00007ffe2fdfc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc5b784000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc5b77f000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007efc5b4a3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc5b27b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efc5d5c5000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007efc5b231000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efc5b211000)
```
and
```
-> Julia 1.9
shell> ldd "/home/alexis/.julia/artifacts/198abd8f4f55bf08c6f84a69e2ad59b3899c9f92/lib/libopenblas.so"
	linux-vdso.so.1 (0x00007fffd45e0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7be7fee000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7be7fe9000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f7be7d0d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7be7ae5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7be9f11000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f7be7a9b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7be7a7b000)
```
And with the Apple M1 used for CI with Julia 1.8:
```
/Users/administrator/.julia/artifacts/4ebb1368465281d712e133a971343fa2fda1c444/lib/libopenblas.0.3.20.dylib:
	@rpath/libopenblas.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
https://github.com/JuliaSmoothOptimizers/HSL.jl/runs/7848247291?check_suite_focus=true#step:6:96

**Comment by dpo** [comment]
So it's ok to use gcc/gfortran-7 on the M1 then?!

**Comment by amontoison** [comment]
The tests passed on Julia nightly. Therefore it seems ok to use gcc/gfortran-7 on the M1.

**Comment by amontoison** [comment]
> So this is where I'm a little confused because Julia 1.6 and 1.7 are based on libgfortran4, whereas Julia ≥ 1.8 is on libgfortran5. And I use gcc/gfortran-7 in all cases, which are based on libgfortran4.

I think that I have the answer @dpo.

Julia ≥ 1.8 is on libgfortran5 for linux:
https://github.com/JuliaSmoothOptimizers/HSL.jl/runs/7849731839?check_suite_focus=true#step:6:116
but it's still libgfortran4 for OSX / M1:
https://github.com/JuliaSmoothOptimizers/HSL.jl/runs/7849731723?check_suite_focus=true#step:6:152
https://github.com/JuliaSmoothOptimizers/HSL.jl/runs/7849731888?check_suite_focus=true#step:6:153

**Comment by dpo** [comment]
I see. That's great, thank you! That also explains why we were a bit confused by each other's experiments.

**Comment by amontoison** [comment]
@JSOBot runtests

**Pull request merged**
