### PR TITLE
Use METIS4_jll instead of METIS_jll

### PR DESCRIPTION
**Pull request by amontoison**
@dpo can you test it on your computer ?

### CODE REVIEW

**Comment by amontoison** [comment]
bump

**Comment by dpo** [comment]
I'm getting
```
(@v1.5) pkg> activate dev-hsl
 Activating new environment at `~/dev/JSO/HSL.jl/dev-hsl/Project.toml`

(dev-hsl) pkg> dev .
[ Info: Resolving package identifier `.` as a directory at `~/dev/JSO/HSL.jl`.
Path `.` exists and looks like the correct package. Using existing path.
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package METIS4_jll [40b5814e]:
 METIS4_jll [40b5814e] log:
 ├─METIS4_jll [40b5814e] has no known versions!
 └─restricted to versions 4.0.3-4 by HSL [34c5aeac] — no versions left
   └─HSL [34c5aeac] log:
     ├─possible versions are: 0.2.1 or uninstalled
     └─HSL [34c5aeac] is fixed to version 0.2.1
```

**Comment by amontoison** [comment]
You need to update your registries.
```julia
pkg> up
```

**Comment by dpo** [comment]
I've been getting this for a few days:
```
┌ Warning: Some registries failed to update:
│     — /Users/dpo/.julia/registries/General — failed to fetch from repo
```
That's probably the reason, but basically, julia won't update the Registry.

**Comment by amontoison** [comment]
You should remove the folder `/Users/dpo/.julia/registries/General`, Julia will automatically regenerate it.

**Comment by amontoison** [comment]
If it works and you can install `HSL`, you should able to use LDLFactorizations.jl with METIS ordering (METIS.jl v1.0) in the same environment.

**Comment by dpo** [comment]
```
ERROR: SystemError: opening file "/Users/dpo/.julia/registries/General/Registry.toml": No such file or directory
```
Awesome that those things go stale...

**Comment by dpo** [comment]
https://github.com/JuliaLang/julia/issues/37521#issuecomment-790781925

**Comment by dpo** [comment]
julialang.org -> 404

I'll try on a different day.

**Comment by amontoison** [comment]
Take my updated registries, it could solve your issues : [General.zip](https://github.com/JuliaSmoothOptimizers/HSL.jl/files/6299799/General.zip)

**Comment by dpo** [comment]
Finally managed after installing Julia 1.6 and dealing with the noisy package manager.

I installed and tested HSL. I was also able to add METIS_jll@5 to the same environment.

**Pull request merged**
