### PR TITLE
Test that we can use Apple Accelerate by default on Mac

### PR DESCRIPTION
**Pull request by amontoison**
It's documented nowhere but I found this in the tests of LBT:
https://github.com/JuliaLinearAlgebra/libblastrampoline/blob/main/test/runtests.jl#L150-L165

We have CI with a M1 so we can test it.

### CODE REVIEW

**Comment by dpo** [comment]
The last time I checked, LAPACK was incomplete in Accelerate.

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
On another note, I don't see the MC21 tests in the output anymore... 🤔

**Comment by amontoison** [comment]
Is it possible to test the following code on your computer Dominique?
You don't need the modifications in this PR to test it.
```julia
# Current version of HSL
using HSL, MatrixMarket, SuiteSparseMatrixCollection
using LinearAlgebra, Printf, BenchmarkTools

ssmc = ssmc_db(verbose=false)
matrix = ssmc_matrices(ssmc, "Boeing", "pwtk")
path = fetch_ssmc(matrix, format="MM")

n = matrix.nrows[1]
A = MatrixMarket.mmread(joinpath(path[1], "$(matrix.name[1]).mtx"))
b = ones(n)
b_norm = norm(b)

# Solve Ax = b.
LDL = @btime Ma57($A)
@btime ma57_factorize($LDL)
@btime ma57_solve($LDL, $b)

blas = "/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/libBLAS.dylib"
lapack = "/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/libLAPACK.dylib"
LinearAlgebra.BLAS.lbt_forward(blas, clear=true, verbose=true)
LinearAlgebra.BLAS.lbt_forward(lapack, clear=false, verbose=true)

# Solve Ax = b.
LDL = @btime Ma57($A)
@btime ma57_factorize($LDL)
@btime ma57_solve($LDL, $b)

**Comment by amontoison** [comment]
> On another note, I don't see the MC21 tests in the output anymore... thinking

I changed `HSL_MC21` into `MC21` with https://github.com/JuliaSmoothOptimizers/HSL.jl/pull/119.
You could use the new variable `HSL_ARCHIVES_PATH` now.

**Comment by dpo** [comment]
```julia
julia> @btime ma57_factorize($LDL)
ERROR: MethodError: no method matching ma57_factorize(::Ma57{Float64})
Closest candidates are:
  ma57_factorize(::SparseArrays.SparseMatrixCSC{T, Ti}; kwargs...) where {T<:Union{Float32, Float64}, Ti<:Integer} at ~/.julia/packages/HSL/X5ozr/src/hsl_ma57.jl:472
```

**Comment by amontoison** [comment]
> ```julia
> julia> @btime ma57_factorize($LDL)
> ERROR: MethodError: no method matching ma57_factorize(::Ma57{Float64})
> Closest candidates are:
>   ma57_factorize(::SparseArrays.SparseMatrixCSC{T, Ti}; kwargs...) where {T<:Union{Float32, Float64}, Ti<:Integer} at ~/.julia/packages/HSL/X5ozr/src/hsl_ma57.jl:472
> ```

It's `ma57_factorize!`.

**Comment by dpo** [comment]
```julia
julia> LDL = @btime Ma57($A)
  499.216 ms (40 allocations: 345.10 MiB)

julia> @btime ma57_factorize!($LDL)
  2.054 s (0 allocations: 0 bytes)

julia> @btime ma57_solve($LDL, $b)
  40.659 ms (4 allocations: 3.33 MiB)
```

After the BLAS change

```julia
julia> LDL = @btime Ma57($A)
  503.579 ms (40 allocations: 345.10 MiB)

julia> @btime ma57_factorize!($LDL)
  1.976 s (0 allocations: 0 bytes)

julia> @btime ma57_solve($LDL, $b)
  45.326 ms (4 allocations: 3.33 MiB)
```

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by amontoison** [comment]
> ```julia
> julia> LDL = @btime Ma57($A)
>   499.216 ms (40 allocations: 345.10 MiB)
> 
> julia> @btime ma57_factorize!($LDL)
>   2.054 s (0 allocations: 0 bytes)
> 
> julia> @btime ma57_solve($LDL, $b)
>   40.659 ms (4 allocations: 3.33 MiB)
> ```
> 
> After the BLAS change
> 
> ```julia
> julia> LDL = @btime Ma57($A)
>   503.579 ms (40 allocations: 345.10 MiB)
> 
> julia> @btime ma57_factorize!($LDL)
>   1.976 s (0 allocations: 0 bytes)
> 
> julia> @btime ma57_solve($LDL, $b)
>   45.326 ms (4 allocations: 3.33 MiB)
> ```

OpenBLAS is already efficient :thinking: , we could keep OpenBLAS32 by default and just add in the documentation how to load MKL or Apple Accelerate #98.

**Comment by dpo** [comment]
Yes, that sounds good.

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
The error with JSOBot is
```
ERROR: Unsatisfiable requirements detected for package libblastrampoline_jll [8e850b90]:
 libblastrampoline_jll [8e850b90] log:
 ├─libblastrampoline_jll [8e850b90] has no known versions!
 └─restricted to versions * by HSL [34c5aeac] — no versions left
   └─HSL [34c5aeac] log:
     ├─possible versions are: 0.3.2 or uninstalled
     └─HSL [34c5aeac] is fixed to version 0.3.2
```
It's stuck on Julia 1.6.

**Comment by amontoison** [comment]
> The error with JSOBot is
> 
> ```
> ERROR: Unsatisfiable requirements detected for package libblastrampoline_jll [8e850b90]:
>  libblastrampoline_jll [8e850b90] log:
>  ├─libblastrampoline_jll [8e850b90] has no known versions!
>  └─restricted to versions * by HSL [34c5aeac] — no versions left
>    └─HSL [34c5aeac] log:
>      ├─possible versions are: 0.3.2 or uninstalled
>      └─HSL [34c5aeac] is fixed to version 0.3.2
> ```
> 
> It's stuck on Julia 1.6.

LBT_jll is shipt with Julia just like OpenBLAS_jll. I don't understand why we have this error. :thinking:

**Comment by dpo** [comment]
Could you test locally with 1.6?

**Comment by amontoison** [comment]
> Could you test locally with 1.6?

I just tested and it works fine.

**Comment by dpo** [comment]
what do we do with this?

**Comment by amontoison** [comment]
We close it and I will add documentation about LBT (#98)

**Pull request closed without merging**
