### PR TITLE
Compile HSL with LBT

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@JSOBot runtests

**Comment by amontoison** [comment]
By default `HSL.jl` will use OpenBLAS32 but we can switch to MKL for instance with LBT:
```
import LinearAlgebra, MKL_jll
LinearAlgebra.BLAS.lbt_forward(MKL_jll.libmkl_rt_path)
```
It should also work with other BLAS backend (Apple Accelerate, BLIS, Fujitsu BLAS, etc...)

**Comment by amontoison** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
# IT WORKS!!!

**Review by dpo — APPROVED** [review]
This is the best thing since sliced bread!!! Thank you!!!

**Pull request merged**
